// ============================================
// SLATE THE LAKES — Product Data
// Generated by Admin Tool on 01/07/2026
// Edit products using the admin tool, then
// export and replace this file in GitHub
// ============================================

const products = [
  {
    "id": "multi-layer-highland-sheep-wall-art",
    "name": "Multi-Layer Highland Sheep Wall Art",
    "collection": "wall-art",
    "badge": "NEW",
    "price": 65,
    "image": "/images/wall-art-layered-sheep.jpg",
    "description": "One of our post popular designs, layered basswood and walnut create this stunning affect.  Looks great mounted on a wall as it does on an optional easel stand",
    "details": [
      "Size: 29 x 29cm",
      "Dispatched by Royal Mail within 2 days",
      "Crafted in Threlkeld, Cumbria"
    ],
    "variants": [],
    "stripeLinks": {},
    "atStall": true,
    "active": true
  }
];
